# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Alex Robertson
tagline:             'A Blog'
description:         'Personal Website/blog of Alex Robertson'
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Alex Robertson
  url:               http://alexrson.github.io/
  email:             alexrson@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"


# Site
site:
  github:
    repo: https://github.com/alexrson/alexrson.github.io
github:
  repo: https://github.com/alexrson/alexrson.github.io
